# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770426f96447734f8eb181db0080671e6f82e1d7ad63073a418f156a8fe33774b5ea9163caebe54022969ab329bc4ab9229d636a351b7bdc2213339e062ae3ed

test:
  secret_key_base: 026ee211c9ef781c0a5a72d08cd089d779219100456fc3b6d4184d4af672d2fc99da62a27598cd85057b5de52618df34221a03ca6310d4909e223898ede365fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
